# Pandas

NumPy creates ndarrays that must contain values that are of the same data type.

Pandas creates dataframes. Each column in a dataframe is an ndarray. This allows us to have traditional tables of data where each column can be a different data type.

In [1]:
import numpy as np
import pandas as pd

The basic data structure in pandas is the *series*. You can construct it in a similar fashion to making a numpy array.

The command to make a Series object is

`pd.Series(data, index=index)`

the `index` argument is optional

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>


In [3]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The series is printed out in a table form.

The type is a Pandas Series

In [4]:
print(data.values)

[0.25 0.5  0.75 1.  ]


In [5]:
print(type(data.values))

<class 'numpy.ndarray'>


The values attribute of the series is a numpy array.

In [6]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)


In [7]:
print(type(data.index))  # the row names are known as the index

<class 'pandas.core.indexes.range.RangeIndex'>


You can subset a pandas series like other python objects

In [8]:
print(data[1])

0.5


In [9]:
print(type(data[1]))  # when you select only one value, it simplifies the object

<class 'numpy.float64'>


In [10]:
print(data[1:3])

1    0.50
2    0.75
dtype: float64


In [11]:
print(type(data[1:3]))  # selecting multiple values returns a series

<class 'pandas.core.series.Series'>


In [12]:
print(data[np.array([1,0,2])])  # fancy indexing using a numpy array

1    0.50
0    0.25
2    0.75
dtype: float64


In [13]:
# specifying the index values
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [14]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
data[1]  # subset with index position

0.5

In [17]:
data["a"]  # subset with index names

0.25

In [18]:
data[0:2]  # slicing behavior is unchanged

a    0.25
b    0.50
dtype: float64

In [19]:
data["a":"c"] # using names includes the last value

a    0.25
b    0.50
c    0.75
dtype: float64

In [20]:
# creating a series from a python dictionary
# remember, dictionary construction uses curly braces {}
samp_dict = {'Archie': 71,
             'Betty': 66,
             'Veronica': 62,
             'Jughead': 72,
             'Cheryl': 66}
samp_series = pd.Series(samp_dict)
samp_series # the series gets alphabetized by its index

Archie      71
Betty       66
Veronica    62
Jughead     72
Cheryl      66
dtype: int64

In [21]:
print(samp_series.index)

Index(['Archie', 'Betty', 'Veronica', 'Jughead', 'Cheryl'], dtype='object')


In [22]:
samp_series.values

array([71, 66, 62, 72, 66], dtype=int64)

In [23]:
print(type(samp_dict))

<class 'dict'>


In [24]:
print(type(samp_series))

<class 'pandas.core.series.Series'>


In [25]:
actor_dict = {'Archie': "KJ",
              'Jughead': "Cole",
              'Betty': "Lili",
              'Veronica': "Camila",
              'Cheryl': "Madelaine"}  # note that the dictionary order is not same here
actor = pd.Series(actor_dict)  # still get alphabetized by index
print(actor)

Archie             KJ
Jughead          Cole
Betty            Lili
Veronica       Camila
Cheryl      Madelaine
dtype: object


# Creating a DataFrame

In [26]:
# we create a dataframe by providing a dictionary of series objects
# the dictionary key becomes the column name
# the dictionary values become values
# the keys within the dictionaries become the indices 
riverdale = pd.DataFrame({'height': samp_series,
                       'actor': actor})  

# the DataFrame will match the indices and sort them
print(riverdale)

          height      actor
Archie        71         KJ
Betty         66       Lili
Cheryl        66  Madelaine
Jughead       72       Cole
Veronica      62     Camila


In [27]:
print(type(riverdale))  # this is a DataFrame object

<class 'pandas.core.frame.DataFrame'>


In [28]:
data = [{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 5}]  # data is a list of dictionaries
# each dictionary needs to have the same set of keys
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 5}]

In [29]:
print(pd.DataFrame(data, index = [1,2,3]))

   a  b
1  0  0
2  1  2
3  2  5


In [30]:
data2 = [{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'c': 5}]  # data is a list of dictionaries
# each dictionary needs to have the same set of keys, otherwise, NAs will appear
data2

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'c': 5}]

In [31]:
pd.DataFrame(data2)  # if the index argument is not supplied, it defaults to integer index start at 0

a    b    c
0  0  0.0  NaN
1  1  2.0  NaN
2  2  NaN  5.0

In [32]:
data3 = {'a' : [1,2,3], 'b': ['x','y','z']} 
# data3 is a dictionary. the keys form column names, and the values are lists of values
data3

{'a': [1, 2, 3], 'b': ['x', 'y', 'z']}

In [33]:
pd.DataFrame(data3)

a  b
0  1  x
1  2  y
2  3  z

In [34]:
data = np.random.randint(10, size = 10).reshape([5,2])
print(data)

[[8 8]
 [0 0]
 [2 5]
 [9 8]
 [7 2]]


In [35]:
print(pd.DataFrame(data, columns = ["x","y"], index = ['a','b','c','d','e']))

   x  y
a  8  8
b  0  0
c  2  5
d  9  8
e  7  2


# Subsetting the DataFrame

In [36]:
print(riverdale)

          height      actor
Archie        71         KJ
Betty         66       Lili
Cheryl        66  Madelaine
Jughead       72       Cole
Veronica      62     Camila


In [37]:
print(riverdale.keys())

Index(['height', 'actor'], dtype='object')


In [38]:
riverdale['actor']  # extracting the column

Archie             KJ
Betty            Lili
Cheryl      Madelaine
Jughead          Cole
Veronica       Camila
Name: actor, dtype: object

In [39]:
riverdale.actor

Archie             KJ
Betty            Lili
Cheryl      Madelaine
Jughead          Cole
Veronica       Camila
Name: actor, dtype: object

In [40]:
riverdale.actor[1]

'Lili'

In [41]:
riverdale.actor['Jughead']

'Cole'

In [42]:
print(riverdale.T)  # prints a copy of the transpose

       Archie Betty     Cheryl Jughead Veronica
height     71    66         66      72       62
actor      KJ  Lili  Madelaine    Cole   Camila


In [43]:
print(riverdale.loc['Jughead']) # subset based on location to get a row

height      72
actor     Cole
Name: Jughead, dtype: object


In [44]:
print(type(riverdale.loc['Jughead']))
print(type(riverdale.loc['Jughead'].values))  # the values are of mixed type but is still a numpy array. 
# this is possible because it is a structured numpy array. (covered in "Python for Data Science" chapter 2)

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [45]:
print(riverdale.loc[:,'height']) # subset based on location to get a column

Archie      71
Betty       66
Cheryl      66
Jughead     72
Veronica    62
Name: height, dtype: int64


In [46]:
print(type(riverdale.loc[:,'height']))  #the object is a pandas series
print(type(riverdale.loc[:,'height'].values))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [47]:
riverdale.loc['Archie','height']  # you can provide a pair of 'coordinates' to get a particular value

71

In [48]:
riverdale.iloc[3,] # subset based on index location

height      72
actor     Cole
Name: Jughead, dtype: object

In [49]:
riverdale.iloc[0, 1] # pair of coordinates

'KJ'

# Importing Data with pd.read_csv()

In [50]:
url = 'https://assets.datacamp.com/production/course_1607/datasets/titanic_sub.csv'
titanic = pd.read_csv(url)

In [51]:
titanic.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [52]:
titanic.shape

(891, 11)

In [53]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [54]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [55]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [56]:
titanic.describe()  # displays summary statistics of the numeric variables

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200